// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDToYo3kjqpuxkNtyUpZEt06gt1JFutKho',
    appId: '1:388071830650:web:627f44305ed6cca51277c3',
    messagingSenderId: '388071830650',
    projectId: 'task-manager-flutter-app-9d761',
    authDomain: 'task-manager-flutter-app-9d761.firebaseapp.com',
    storageBucket: 'task-manager-flutter-app-9d761.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVsCFoFqPUVPLYp2dALRDFSFA0UtCJkBk',
    appId: '1:388071830650:android:d8f52382afef80ea1277c3',
    messagingSenderId: '388071830650',
    projectId: 'task-manager-flutter-app-9d761',
    storageBucket: 'task-manager-flutter-app-9d761.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-nZ3bZ0E8JJf5uHFDB9ImqkU85ow7Prc',
    appId: '1:388071830650:ios:6e7fd969d350d20e1277c3',
    messagingSenderId: '388071830650',
    projectId: 'task-manager-flutter-app-9d761',
    storageBucket: 'task-manager-flutter-app-9d761.firebasestorage.app',
    iosClientId: '388071830650-i2004snqenjgvmhkg8pr49miua3cnbuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-nZ3bZ0E8JJf5uHFDB9ImqkU85ow7Prc',
    appId: '1:388071830650:ios:6e7fd969d350d20e1277c3',
    messagingSenderId: '388071830650',
    projectId: 'task-manager-flutter-app-9d761',
    storageBucket: 'task-manager-flutter-app-9d761.firebasestorage.app',
    iosClientId: '388071830650-i2004snqenjgvmhkg8pr49miua3cnbuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDToYo3kjqpuxkNtyUpZEt06gt1JFutKho',
    appId: '1:388071830650:web:719ef966c083945c1277c3',
    messagingSenderId: '388071830650',
    projectId: 'task-manager-flutter-app-9d761',
    authDomain: 'task-manager-flutter-app-9d761.firebaseapp.com',
    storageBucket: 'task-manager-flutter-app-9d761.firebasestorage.app',
  );
}
